package personServlet;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(loadOnStartup = 1, urlPatterns = "/munthiri")
public class PersonServlet extends HttpServlet {

	public PersonServlet() {
		System.out.println("crreat person servlet ");
	}

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		System.out.println("create a get method invoke");
		String name = req.getParameter("name");
		String gender = req.getParameter("Gender");
		String DOB = req.getParameter("DOB");
		String petName = req.getParameter("PetName");
		String nativePlace = req.getParameter("native Place");
		String phoneNo = req.getParameter("PhoneNo");
		String emailId = req.getParameter("EmailId");
		String passportNo = req.getParameter("Passport No");
		String rationCardNo = req.getParameter("RationCardNo");
		String heighestEducation = req.getParameter("HeighestEducation");
		String loverName = req.getParameter("LoverName");
		String exLoverName = req.getParameter("ExLoverName");
		String breakups = req.getParameter("Breakup's");
		String breakupReson = req.getParameter("BreakupReson");
		String workingPlace = req.getParameter("working place");
		String post = req.getParameter("Post");
		String postalCode = req.getParameter("postalCode");
		String hobli = req.getParameter("Hobli");
		String taluk = req.getParameter("Taluk");
		String district = req.getParameter("District");
		String fatherName = req.getParameter("FatherName");
		String motherName = req.getParameter("MotherName");
		String brotherName = req.getParameter("BrotherName");
		String sisterName = req.getParameter("SisterName");
		String grandFatherName = req.getParameter("GrandFatherName");
		String grandMotherName = req.getParameter("GrandMotherName");
		String uncleName = req.getParameter("UncleName");
		String auntiName = req.getParameter("AuntiName");
		String maritalStatus = req.getParameter("marital status");
		String wifeName = req.getParameter("WifeName");
		String husbendName = req.getParameter("HusbendName");
		String children = req.getParameter("Children");

		String studentName = req.getParameter("StudentName");
		String studentRegNo = req.getParameter("StudentRegNo");
		String schoolName = req.getParameter("SchoolName");
		String schoolPlace = req.getParameter("SchoolPlace");
		String HMName = req.getParameter("HMName");
		String classTeacherName = req.getParameter("ClassTeacherName");
		String classLeaderName = req.getParameter("ClassLeaderName");
		String totalStudent = req.getParameter("TotalStudent");
		String totalSubjec = req.getParameter("TotalSubjec");
		String favSubject = req.getParameter("FavSubject");
		String sSLCPercentage = req.getParameter("SSLCPercentage");
		String pUCYearOfPassing = req.getParameter("PUCYearOfPassing");
		String collegeName = req.getParameter("CollegeName");
		String location = req.getParameter("Location");
		String combination = req.getParameter("Combination");
		String teacherName = req.getParameter("TeacherName");
		String principalName = req.getParameter("PrincipalName");
		String totalSubject = req.getParameter("TotalSubject");
		String totalLab = req.getParameter("totalLab");
		String yearOfPassing = req.getParameter("YearOfPassing");
		String result = req.getParameter("Result");
		String percentage = req.getParameter("Percentage");
		String degreeCollegeName = req.getParameter("DegreeCollegeName");
		String collagePlace = req.getParameter("CollagePlace");
		String pricipalName = req.getParameter("PricipalName");
		String univercityName = req.getParameter("UnivercityName");
		String totalSem = req.getParameter("TotalSem");
		String totalYear = req.getParameter("TotalYear");
		String classLeader = req.getParameter("ClassLeader");
		String totalProjects = req.getParameter("TotalProjects");
		String totalLabs = req.getParameter("totalLabs");
		String dResult = req.getParameter("DResult");
		String totalPercentage = req.getParameter("TotalPercentage");
		String requiredMarks = req.getParameter("RequiredMarks");

		String favColor = req.getParameter("favColor");
		String favFood = req.getParameter("favFood");
		String favBike = req.getParameter("favBike");
		String favCar = req.getParameter("favCar");
		String favShoesBrand = req.getParameter("favShoesBrand");
		String favSunGlass = req.getParameter("favSunGlass");
		String favPlace = req.getParameter("favPlace");
		String favMovie = req.getParameter("favMovie");
		String favSong = req.getParameter("favSong");
		String favMobile = req.getParameter("favMobile");
		String favLaptop = req.getParameter("favLaptop");
		String favClothBrand = req.getParameter("favClothBrand");
		String favCompany = req.getParameter("favCompany");
		String favSlipper = req.getParameter("favSlipper");
		String favTiffin = req.getParameter("favTiffin");
		String favHotel = req.getParameter("favHotel");
		String closeFriend = req.getParameter("closeFriend");
		String dreamCompany = req.getParameter("dreamCompany");
		String fevBook = req.getParameter("fevBook");
		String fevNewsChannel = req.getParameter("fevNewsChannel");
		String fevCEO = req.getParameter("fevCEO");
		String fevPoliticalParty = req.getParameter("fevPoliticalParty");
		String fevCM = req.getParameter("fevCM");
		String fevPM = req.getParameter("fevPM");
		String fevPoet = req.getParameter("fevPoet");
		String familyDoctor = req.getParameter("familyDoctor");
		String familyLoyer = req.getParameter("familyLoyer");
		String familyCA = req.getParameter("familyCA");

		System.out.println("name:" + name);
		System.out.println("gender:" + gender);
		System.out.println("DOB:" + DOB);
		System.out.println("petName:" + petName);
		System.out.println("nativePlace:" + nativePlace);
		System.out.println("phoneNo:" + phoneNo);
		System.out.println("emailId:" + emailId);
		System.out.println("passportNo:" + passportNo);
		System.out.println("rationCardNo:" + rationCardNo);
		System.out.println("heighestEducation:" + heighestEducation);
		System.out.println("loverName:" + loverName);
		System.out.println("exLoverName:" + exLoverName);
		System.out.println("breakups:" + breakups);
		System.out.println("breakupReson:" + breakupReson);
		System.out.println("workingPlace:" + workingPlace);
		System.out.println("post:" + post);
		System.out.println("postalCode:" + postalCode);
		System.out.println("hobli:" + hobli);
		System.out.println("taluk:" + taluk);
		System.out.println("district:" + district);
		System.out.println("fatherName:" + fatherName);
		System.out.println("motherName:" + motherName);
		System.out.println("brotherName:" + brotherName);
		System.out.println("sisterName:" + sisterName);
		System.out.println("grandFatherName:" + grandFatherName);
		System.out.println("grandMotherName:" + grandMotherName);
		System.out.println("uncleName:" + uncleName);
		System.out.println("auntiName:" + auntiName);
		System.out.println("maritalStatus:" + maritalStatus);
		System.out.println("wifeName:" + wifeName);
		System.out.println("husbendName:" + husbendName);
		System.out.println("children:" + children);

		System.out.println("studentName:" + studentName);
		System.out.println("studentRegNo:" + studentRegNo);
		System.out.println("schoolName:" + schoolName);
		System.out.println("schoolPlace:" + schoolPlace);
		System.out.println("HMName:" + HMName);
		System.out.println("classTeacherName:" + classTeacherName);
		System.out.println("classLeaderName:" + classLeaderName);
		System.out.println("totalStudent:" + totalStudent);
		System.out.println("totalSubjec:" + totalSubjec);
		System.out.println("favSubject:" + favSubject);
		System.out.println("sSLCPercentage:" + sSLCPercentage);
		System.out.println("pUCYearOfPassing:" + pUCYearOfPassing);
		System.out.println("collegeName:" + collegeName);
		System.out.println("location:" + location);
		System.out.println("combination:" + combination);
		System.out.println("teacherName:" + teacherName);
		System.out.println("principalName:" + principalName);
		System.out.println("totalSubject:" + totalSubject);
		System.out.println("totalLab:" + totalLab);
		System.out.println("yearOfPassing:" + yearOfPassing);
		System.out.println("result:" + result);
		System.out.println("percentage:" + percentage);
		System.out.println("degreeCollegeName:" + degreeCollegeName);
		System.out.println("collagePlace:" + collagePlace);
		System.out.println("pricipalName:" + pricipalName);
		System.out.println("univercityName:" + univercityName);
		System.out.println("totalSem:" + totalSem);
		System.out.println("totalYear:" + totalYear);
		System.out.println("classLeader:" + classLeader);
		System.out.println("totalProjects:" + totalProjects);
		System.out.println("totalLabs:" + totalLabs);
		System.out.println("dResult:" + dResult);
		System.out.println("totalPercentage:" + totalPercentage);
		System.out.println("requiredMarks:" + requiredMarks);

		System.out.println("favColor:" + favColor);
		System.out.println("favFood:" + favFood);
		System.out.println("favBike:" + favBike);
		System.out.println("favCar:" + favCar);
		System.out.println("favShoesBrand:" + favShoesBrand);
		System.out.println("favSunGlass:" + favSunGlass);
		System.out.println("favPlace:" + favPlace);
		System.out.println("favMovie:" + favMovie);
		System.out.println("favSong:" + favSong);
		System.out.println("favMobile:" + favMobile);
		System.out.println("favLaptop:" + favLaptop);
		System.out.println("favClothBrand:" + favClothBrand);
		System.out.println("favCompany:" + favCompany);
		System.out.println("favSlipper:" + favSlipper);
		System.out.println("favTiffin:" + favTiffin);
		System.out.println("favHotel:" + favHotel);
		System.out.println("closeFriend:" + closeFriend);
		System.out.println("dreamCompany:" + dreamCompany);
		System.out.println("fevBook:" + fevBook);
		System.out.println("fevNewsChannel:" + fevNewsChannel);
		System.out.println("fevCEO:" + fevCEO);
		System.out.println("fevPoliticalParty:" + fevPoliticalParty);
		System.out.println("fevCM:" + fevCM);
		System.out.println("fevPM:" + fevPM);
		System.out.println("fevPoet:" + fevPoet);
		System.out.println("familyDoctor:" + familyDoctor);
		System.out.println("familyLoyer:" + familyLoyer);
		System.out.println("familyCA:" + familyCA);
		super.doGet(req, resp);
	}

}
